### ISSUE TITLE
I don't know how to use this

### ISSUE THREAD

**Issue by moyoron64** [jiahansu/GazeJS#2] opened 2015-09-30 07:23 UTC
I'm very Beginner....
Please help!!

I don't know how to use this.
When I use this ,arise error.「Cannot find module 'myclass'」
what should I do?please help ....

**Comment by jonathan-reisdorf** [comment] 2015-09-30 07:42
You will need to call `npm install` before you can start using the node modules required by this project.
This job is automatically done when you do `npm install gazejs`

If that doesn't work you can of course also locally clone this repo first:

```
mkdir myproject
cd myproject
git clone https://github.com/jiahansu/GazeJS.git
cd GazeJS
npm install
cd ..
```

then create a new .js file in the myproject folder and copy the code from the readme, but change the first line to `var gazejs = require("./GazeJS");`

That should help in case something didn't work out with the npm package

**Comment by moyoron64** [comment] 2015-09-30 08:11
thanks!!
I was going to try to as it was said of you...
but next came out different error...「Cannot find module 'bridjs'」
please help ...

**Comment by jonathan-reisdorf** [comment] 2015-09-30 08:14
Hmm.. Usually when you do npm install, all of the dependencies declared in the package.json are installed. In our case here that includes bridjs.
I guess you did npm install, but something did not work out during the installation of the bridjs module.
Can you tell me which OS you are using?
For bridjs there is a step where it needs to compile something, so it is very well possible that your system failed during compiling that stuff.

**Comment by moyoron64** [comment] 2015-09-30 08:36
I use Windows7.
Situation is like this....

![folder](https://cloud.githubusercontent.com/assets/8488745/10188349/908fb89e-6799-11e5-8eff-a5fa39ae3ca1.png)
![mytest](https://cloud.githubusercontent.com/assets/8488745/10188351/9091ed12-6799-11e5-9f87-395952141b18.png)
![folder2](https://cloud.githubusercontent.com/assets/8488745/10188350/90903e54-6799-11e5-8097-612402b90e9d.png)
![gitshell](https://cloud.githubusercontent.com/assets/8488745/10188352/9094d270-6799-11e5-8c7e-f761b74c16d2.png)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 08:43
OK, in your case what you did wrong is npm install gazejs while being in the locally cloned gazejs folder. Instead what you should be doing is just run npm install (without specifying what to install) - that means that npm looks into the package.json and installs all the stuff listed there

**Comment by moyoron64** [comment] 2015-09-30 08:56
It is something like this?
I am sorry but　I want you to tell me a little more in detail the procedure if you can...

![1](https://cloud.githubusercontent.com/assets/8488745/10188669/285a4890-679c-11e5-84bc-01035f25ede8.png)
![2](https://cloud.githubusercontent.com/assets/8488745/10188668/2854fa98-679c-11e5-8614-93fd32c36fff.png)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 09:02
OK, so you need to install python first and have it available in the command line. Grab a 64 bit release of version 2 from here: https://www.python.org/downloads/windows/
Then restart your cmd and see if python runs if you just type python. If it doesn't know the command, you have to get the path of the executable and add it to the PATH variable.

Once you have done that also try running cl in your cmd. If that command is not there it means that you do not have Visual Studio installed OR that the path containing the cl executable is not added to the PATH variable as well. You will need Visual Studio 2013 Express (or higher) to get this thing compiled.

Side note: To permanently add something to the PATH variable, you can do so by calling:

```
setx path "%path%;C:\path\to\directory\where\the\executable\file\is\in\"
```

(see also here: http://stackoverflow.com/questions/9546324/adding-directory-to-path-environment-variable-in-windows where you will also find other ways to do so)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 09:10
To save you some work, after installing Visual Studio 2013 you can also run this in command line:

call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86

if that works the cl command will be available until you close the cmd instance

**Comment by moyoron64** [comment] 2015-09-30 10:57
Thank you very much!
I installed python and were able to use the cl.
I think that It can be in a little more!!
but next came out different error....
Please lend your power to me again....

![5](https://cloud.githubusercontent.com/assets/8488745/10191287/89b52d88-67ad-11e5-9f2f-b207bb85a354.png)

初期化中　＝During initialization
変換できません = can not convert

コンストラクターはソース型を持てません、またはコンストラクターのオーバーロードの解決があいまいです。　＝
Constructor can not have a source type, or resolution of overloaded constructor is ambiguous.

コードを生成中　＝　while generating code

**Comment by jonathan-reisdorf** [comment] 2015-09-30 10:58
Hi, the important part of your command line output is missing from the screenshot..

**Comment by moyoron64** [comment] 2015-09-30 11:10
Sorry,This okay?

![9](https://cloud.githubusercontent.com/assets/8488745/10191475/329b22f8-67af-11e5-91e6-1dae61fca98a.png)
![10](https://cloud.githubusercontent.com/assets/8488745/10191476/329e2a7a-67af-11e5-9c30-a510e4e4d158.png)

初期化中　＝During initialization
変換できません = can not convert

コンストラクターはソース型を持てません、またはコンストラクターのオーバーロードの解決があいまいです。　＝
Constructor can not have a source type, or resolution of overloaded constructor is ambiguous.

コードを生成中　＝　while generating code

**Comment by jonathan-reisdorf** [comment] 2015-09-30 11:30
Not within my general knowledge, but this line is causing the error:
https://github.com/jiahansu/BridJS/blob/master/src/dyncall_v8_utils.cc#L228
That's weird because in line 225 you can see that it just gets to that point if the node major version is < 4, which does not seem to be the case in your system (node -v)
When I had to compile it last time, I had node v0.12.4 and it worked fine

**Comment by jonathan-reisdorf** [comment] 2015-09-30 11:38
OK, actually there is a compatibility issue with node 4, but it got fixed with this commit: https://github.com/jiahansu/BridJS/commit/65d143002fe04b067def611d3102a398e4adb64a

So basically all you have to do is:
Go into the bridjs directory and call: npm install bridjs@0.3.4-3

@jiahansu you could npm update the package file :)

**Comment by moyoron64** [comment] 2015-09-30 12:36
came out  error....
I think that It can be in a little more...

I'm sorry in Japanese
translate the yellow part...
「LINK : warning LNK4098: defaultlib 'LIBCMT'　conflict with the use of other libraries. 
/ NODEFAULTLIB: Please use this library. 
[H:\test2\bridjs\BridJS\node_modules\bridjs\build\bridjs.vcxproj]」

Can you lend a little more just power?

![11](https://cloud.githubusercontent.com/assets/8488745/10192901/a300dde8-67ba-11e5-9315-5371f8bdc967.png)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 12:38
As long as it's just a warning (yellow, not red), the compiling is done and you're fine. Try now to run your project code again.

**Comment by moyoron64** [comment] 2015-09-30 12:46
It came out the same error as before...
translate the yellow part...
「.. \ src \ dyncall_v8_utils.cc (229): error C2440: 'initializing': 'v8 :: MaybeLocal <v8 :: Object>' from 'v8 :: Local <v8 :: Object>' can not be converted to. [H: \ test2 \ myproject \ GazeJS \ node_modules \ bridjs \ build \ bridjs.vcxproj]」

![111](https://cloud.githubusercontent.com/assets/8488745/10193188/729594bc-67bc-11e5-9ca2-d39fb2171251.png)
![1111](https://cloud.githubusercontent.com/assets/8488745/10193190/735e0578-67bc-11e5-887a-b5a964425d4b.png)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 12:49
Of course it does, that's because you ran npm install on the old stuff again.
What I was telling you is: Please now leave the gazejs folder, go back into your project folder and run your project javascript file (mytest.js).
As now you have again tried to install the old version of bridjs, please revert that action by again calling npm install bridjs@0.3.4-3
;)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 12:55
So just again for the record: calling npm install without any parameters means: Please install all the modules that are described within the package.json using the version numbers described there. We found out that the package version used in the package.json (0.2.0-9) does not work on your computer. That's why we manually installed a higher version (0.3.4-3). No npm install necessary afterwards, as that would try to bring back the older version unless you change the package.json, which I asked the author to do in the future.

**Comment by moyoron64** [comment] 2015-09-30 12:56
Output has changed!
![11111](https://cloud.githubusercontent.com/assets/8488745/10193432/11437588-67be-11e5-8ee1-467098d1826b.png)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 12:57
as a quickfix, transform all occurencies in your project file from log.info to console.log

**Comment by moyoron64** [comment] 2015-09-30 13:05
next came out different error　:'-(
![12](https://cloud.githubusercontent.com/assets/8488745/10193645/4e9dffe2-67bf-11e5-888e-7ab877a745eb.png)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 13:06
OK man. Have you ever worked with javascript beforehand?
It's not console.log.info
It's console.log
console.info is also possible

**Comment by moyoron64** [comment] 2015-09-30 13:14
Sorry,I  never used javascript until now...
So to you I am really grateful.

An error has disappeared!
What do I in order to display a circle to GoogleChorome as the demo movie?

![123](https://cloud.githubusercontent.com/assets/8488745/10193821/466bb570-67c0-11e5-9b73-5653b847c563.png)

**Comment by jonathan-reisdorf** [comment] 2015-09-30 13:17
OK, your issue has been resolved and can be marked closed. Sorry but the bug tracker here is intended for real bugs. The code now works as intended, so you will have to find out the rest on your own.
Despite, this project is perhaps not suitable for you since you are an absolute beginner in JavaScript. You should definitely learn how to use the language first and then continue working on this.

**Comment by moyoron64** [comment] 2015-09-30 13:21
OK,I see !
I apologize for the inconvenience really.I was really saved.
Thank you very much!!I am delighted that it was able to meet you.

**Closed as completed** 2015-09-30 16:42 UTC

**Comment by jiahansu** [comment] 2015-10-11 16:11
Hi, moyoron64

Congratulation !! You are able to run GazeJS on your environment
But GazeJS  is just a simple library to access Tobii Gaze SDK by Nodejs
If you want  do something like demo video, it is a long journey to you!!
The GazeJS can be integrated with NW.js (http://nwjs.io/) and you can access browser and GazeJS on the same program.

I am preparing to host a new project, named EyeShell, it allow you to access gaze tracking features on NW.js more easily. It will support Tobii Gaze SDK and SR research EyeLink....
